export const colorOptions = [
    { name: 'Blue',    value: '#4A90E2' },
    { name: 'Green',   value: '#50E3C2' },
    { name: 'Orange',  value: '#F5A623' },
    { name: 'Red',     value: '#D0021B' },
    { name: 'Purple',  value: '#9013FE' },
    { name: 'Teal',    value: '#008080' },
    { name: 'Yellow',  value: '#F8E71C' },
    { name: 'Pink',    value: '#E91E63' },
    { name: 'Indigo',  value: '#3F51B5' },
    { name: 'Cyan',    value: '#00BCD4' },
    { name: 'Lime',    value: '#CDDC39' },
    { name: 'Amber',   value: '#FFC107' },
    { name: 'Brown',   value: '#795548' },
    { name: 'Gray',    value: '#9E9E9E' },
    { name: 'Navy',    value: '#2C3E50' },
    { name: 'Coral',   value: '#FF7F50' },
    { name: 'Turquoise', value: '#1ABC9C' },
    { name: 'Lavender',  value: '#B39DDB' },
];
